[build]
command = "streamlit run streamlit_frontend/Home.py"
publish = "streamlit_frontend"
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.11"
STREAMLIT_SERVER_PORT = "8501"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "streamlit"
targetPort = 8501

[functions]
directory = "netlify/functions"
node_bundler = "esbuild" 