[build]
command = "pip install -r requirements.txt"
functions = "netlify/functions"
publish = "streamlit_frontend"

[build.environment]
PYTHON_VERSION = "3.8"
PYTHONPATH = "."

[[redirects]]
from = "/*"
to = "/.netlify/functions/streamlit"
status = 200
force = true

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[dev]
framework = "#custom"
port = 8501 