[build]
command = """
pip install -r requirements.txt &&
streamlit run streamlit_frontend/Home.py --server.port $PORT --server.address 0.0.0.0
"""
publish = "streamlit_frontend"

[build.environment]
PYTHON_VERSION = "3.9"
PORT = "8501"

[[redirects]]
force = true
from = "/*"
status = 200
to = "/"

[dev]
command = "streamlit run streamlit_frontend/Home.py"
framework = "#custom"
port = 8501

[[plugins]]
package = "@netlify/plugin-functions-install-core" 