[build]
command = "./netlify_build.sh"
publish = "streamlit_frontend"

[build.environment]
PYTHON_VERSION = "3.8.10"
PYTHONPATH = "."
NODE_VERSION = "16"
PORT = "8501"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[dev]
command = "./netlify_build.sh"
framework = "#custom"
port = 8501

[[plugins]]
package = "@netlify/plugin-functions-core" 