[build]
command = "pip install -r requirements.txt && streamlit run streamlit_frontend/Home.py"
publish = "streamlit_frontend"

[build.environment]
PYTHON_VERSION = "3.8"
PYTHONUNBUFFERED = "1"

[[redirects]]
from = "/*"
to = "/.netlify/functions/streamlit"
status = 200

[functions]
directory = "netlify/functions"

[dev]
command = "streamlit run streamlit_frontend/Home.py"
targetPort = 8501

[[plugins]]
package = "@netlify/plugin-functions-install-core" 